name: squaring

services:
  hardhat:
    image: pelldvs-squaring-hardhat:latest
    environment:
      - LOCALHOST_URL=http://eth:8545
    depends_on:
      eth:
        condition: service_started
    healthcheck:
      test: [ "CMD", "test", "-f", "/root/contracts_deployed_completed" ]
      start_period: 50s
      retries: 3
      interval: 10s

  eth:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - "${ETH_HOST_PORT:-8747}:8545"
    entrypoint: [ "anvil", "--host", "0.0.0.0", "--chain-id", "1337", "--state", "/tmp/anvil.state.json" ]
    platform: ${PLATFORM:-linux/amd64}
    healthcheck:
      test: [ "CMD", "cast", "block-number" ]
      retries: 3
      interval: 10s

  emulator:
    image: pelldvs-squaring-pelldvs:local-version
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
    depends_on:
      hardhat:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/init_emulator.sh" ]
    ports:
      - "${EMULATOR_HOST_PORT:-9191}:9090"
    volumes:
      - ./pelldvs/scripts:/root/scripts
    healthcheck:
      test: [ "CMD", "test", "-f", "/root/emulator_initialized" ]
      start_period: 50s
      retries: 3
      interval: 10s

  dvs:
    image: pelldvs-squaring-operator:local-version
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
      - GITHUB_TOKEN=$GITHUB_TOKEN
    depends_on:
      emulator:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/local-start_dvs.sh" ]
    volumes:
      - ./pelldvs/scripts:/root/scripts
      - ../:/app

  gateway:
    image: pelldvs-squaring-operator:local-version
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
    depends_on:
      emulator:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/start_task_gateway.sh" ]
    volumes:
      - ./task_gateway/scripts:/root/scripts
    healthcheck:
      test: [ "CMD", "test", "-f", "/root/task_gatewa_initialized" ]
      start_period: 50s
      retries: 3
      interval: 10s

  operator01:
    image: pelldvs-squaring-operator:local-version
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
      - OPERATOR_NODE_NAME=operator01
    depends_on:
      dvs:
        condition: service_started
      gateway:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/start_operator.sh" ]
    volumes:
      - ./operator/scripts:/root/scripts
    healthcheck:
      test: [ "CMD", "test", "-f", "/root/operator_initialized" ]
      start_period: 50s
      retries: 3
      interval: 10s

  operator02:
    image: pelldvs-squaring-operator:local-version
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
      - OPERATOR_NODE_NAME=operator02
    depends_on:
      dvs:
        condition: service_started
      gateway:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/start_operator.sh" ]
    volumes:
      - ./operator/scripts:/root/scripts
    healthcheck:
      test: [ "CMD", "test", "-f", "/root/operator_initialized" ]
      start_period: 50s
      retries: 3
      interval: 10s

  test:
    image: pelldvs-squaring-operator:local-version
    environment:
      - ETH_RPC_URL=http://eth:8545
      - ETH_WS_URL=ws://eth:8545
      - TIMEOUT_FOR_TASK_PROCESS=${TIMEOUT_FOR_TASK_PROCESS:-10}
    depends_on:
      operator01:
        condition: service_started
      operator02:
        condition: service_started
      gateway:
        condition: service_started
    entrypoint: [ "bash", "/root/scripts/test.sh" ]
    volumes:
      - ./operator/scripts:/root/scripts
