name: pelldvs-squaring

services:
  hardhat:
    build:
      context: ./
      dockerfile: ./contracts/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - GITHUB_TOKEN=$GITHUB_TOKEN
        - CONTRACT_VERSION=v0.1.0

  pelldvs:
    image: pelldvs-squaring-pelldvs:local-version
    build:
      context: ./
      dockerfile: ./pelldvs/Dockerfile-local
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - GITHUB_TOKEN=$GITHUB_TOKEN
        - PELLDVS_VERSION=v0.2.1 # this will be ignored

  operator:
    image: pelldvs-squaring-operator:local-version
    build:
      context: ../
      dockerfile: ./docker/operator/Dockerfile-local
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - GITHUB_TOKEN=$GITHUB_TOKEN
        - PELLDVS_VERSION=v0.2.1 # this will be ignored
