name: squaring

services:
  dvs:
    image: pelldvs-example-testnet-pelldvs:latest
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - ETH_WS_URL=${ETH_WS_URL}
      - REGISTRY_ROUTER_ADDRESS=${REGISTRY_ROUTER_ADDRESS}
      - NETWORK=${NETWORK}
      - CHAIN_ID=${CHAIN_ID}
      - SERVICE_CHAIN_RPC_URL=${SERVICE_CHAIN_RPC_URL}
      - SERVICE_CHAIN_WS_URL=${SERVICE_CHAIN_WS_URL}
      - AGGREGATOR_RPC_PORT=${AGGREGATOR_RPC_PORT:-26653}
      - AGGREGATOR_INDEXER_BATCH_SIZE=${AGGREGATOR_INDEXER_BATCH_SIZE:-100}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    entrypoint: [ "bash", "/root/scripts/start_dvs.sh" ]
    ports:
      - "${AGGREGATOR_HOST_DEBUG_PORT:-3346}:${DEBUG_PORT:-2345}"
      - "${AGGREGATOR_HOST_SERVER_PORT:-25653}:${AGGREGATOR_RPC_PORT:-26653}"
    volumes:
      - ${HOST_PELLDVS_HOME:-./.pelldvs}:/root/.pelldvs
      - ./dvs:/root/scripts
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  gateway:
    image: pelldvs-example-testnet-operator:latest
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - ETH_WS_URL=${ETH_WS_URL}
      - NETWORK=${NETWORK}
      - CHAIN_ID=${CHAIN_ID}
      - GATEWAY_KEY=${GATEWAY_KEY}
      - SERVICE_CHAIN_RPC_URL=${SERVICE_CHAIN_RPC_URL}
      - AGGREGATOR_RPC_SERVER=${AGGREGATOR_RPC_SERVER} # public URL of the aggregator
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    entrypoint: [ "bash", "/root/scripts/start_gateway.sh" ]
    ports:
      - "${GATEWAY_HOST_DEBUG_PORT:-3347}:${DEBUG_PORT:-2345}"
      - "${GATEWAY_HOST_SERVER_PORT:-8949}:${GATEWAY_PORT:-8949}"
    volumes:
      - ${HOST_PELLDVS_HOME:-./.pelldvs}:/root/.pelldvs
      - ./dvs:/root/scripts
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  default:
    name: pelldvs-squaring-devnet