name: Build
# Tests runs different tests (test_avsi_apps, test_avsi_cli, test_apps)
# This workflow runs on every push to v0.38.x and every pull request
# All jobs will pass without running if no *{.go, .mod, .sum} files have been modified
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: [ "self-hosted", "Linux", "X64", "ci" ]
    strategy:
      fail-fast: false
      matrix:
        goarch: [ "arm64", "amd64" ]
        goos: [ "linux" ]
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      TAG: ${{ github.event.pull_request.head.sha || github.workflow_sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.go
            "!test/"
            go.mod
            go.sum
            Makefile
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
        if: env.GIT_DIFF
      - name: private
        run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
        if: env.GIT_DIFF
      - name: build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build
        if: "env.GIT_DIFF != ''"
