name: e2e
# Runs the CI end-to-end test network on all pushes to v0.38.x
# and every pull request, but only if any Go files have been changed.
on:
  workflow_dispatch: # allow running workflow manually
  pull_request:
  push:
    branches:
      - dev
jobs:
  e2e-test:
    runs-on: [ "self-hosted", "Linux", "X64", "ci" ]
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      TAG: ${{ github.event.pull_request.head.sha || github.workflow_sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: private
        run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
      - name: Build docker images
        run: make docker-build-all
      - name: Stop services
        run: make docker-all-down
      - name: Start services
        run: make docker-up-operator
      - name: Check docker service status
        run: make docker-all-status
      - name: Test services
        run: make docker-test
        env:
          TIMEOUT_FOR_TASK_PROCESS: 20
      - name: Stop services
        run: make docker-all-down
        if: always()
